server {
    listen 80 default_server;
    listen [::]:80 default_server;

    # Bật ModSecurity cho server block này
    modsecurity on;
    modsecurity_rules_file /etc/nginx/modsecurity.d/include.conf;

    location / {
        # Đảm bảo ModSecurity cũng được bật ở location
        modsecurity on;
        
        # Trả về trang mẫu để test
        default_type text/html;
        return 200 "OK - WAF Lab Active";
    }
}