server {
    listen 80 default_server;
    listen [::]:80 default_server;

    # 1. Bật ModSecurity engine
    modsecurity on;

    # 2. Nạp bộ luật CRS đã chuẩn bị sẵn bởi entrypoint
    modsecurity_rules_file /etc/nginx/modsecurity.d/include.conf;

    location / {
        default_type text/html;
        return 200 "OK - WAF Security Lab Active";
    }
}