server {
    listen 80 default_server;
    listen [::]:80 default_server;

    modsecurity on;

    location / {
        default_type text/html;
        return 200 "OK - WAF Security Lab Active";
    }
}