SecRuleEngine On
SecRequestBodyAccess On
SecResponseBodyAccess Off
SecResponseBodyMimeType text/html text/plain text/xml
SecDataDir /tmp/modsecurity/data

# Thiết lập hành động mặc định: Chặn ngay lập tức với mã lỗi 403
SecDefaultAction "phase:1,log,auditlog,deny,status:403"
SecDefaultAction "phase:2,log,auditlog,deny,status:403"