server {
    listen 80 default_server;
    listen [::]:80 default_server;

    # Bật ModSecurity Module
    modsecurity on;

    # Nạp file override đã được script container generate (chứa SecRuleEngine On)
    modsecurity_rules_file /etc/nginx/modsecurity.d/modsecurity-override.conf;

    location / {
        default_type text/html;
        return 200 "OK - WAF Security Lab Active";
    }
}