server {
    listen 80 default_server;
    listen [::]:80 default_server;

    # Bật ModSecurity engine
    modsecurity on;

    # Bắt buộc chuyển sang chế độ Blocking (Chặn) ngay tại đây
    modsecurity_rules '
        SecRuleEngine On
    ';

    location / {
        default_type text/html;
        return 200 "OK - WAF Security Lab Active";
    }
}