server {
    listen 80 default_server;
    listen [::]:80 default_server;

    # Bật ModSecurity (Nginx container tự nạp các file rules chuẩn)
    modsecurity on;

    location / {
        default_type text/html;
        return 200 "OK - WAF Security Lab Active";
    }
}